tag_groups:
- name: env
  tags:
  - name: env
    value:
        default: demo
    filters:
      tags:
        git_repo: yor_poc
      directory: /terraform/demo
- name: team
  tags:
  - name: team
    value:
        default: devops
    filters:
      tags:
        git_repo: yor_poc
      directory: /terraform/yor

-